package com.udd.forensic.service;

import com.udd.forensic.dto.ForensicReportDTO;
import com.udd.forensic.model.ForensicReport;
import com.udd.forensic.repository.ForensicReportRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.elasticsearch.core.geo.GeoPoint;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.security.MessageDigest;
import java.util.HexFormat;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Main service for managing forensic reports.
 * Orchestrates the full pipeline:
 *   1. Upload PDF to MinIO (auto-generated or user-provided)
 *   2. Extract text via Apache Tika
 *   3. Build ForensicReport entity
 *   4. Save to Elasticsearch
 *   5. Log statistics for Logstash/Kibana
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ForensicReportService {

    private final ForensicReportRepository repository;
    private final MinioService minioService;
    private final TikaService tikaService;
    private final StatsService statsService;
    private final PdfGenerationService pdfGenerationService;

    /**
     * Creates a new forensic report from metadata.
     * PDF is optional – if not provided, the system auto-generates one from the form data.
     *
     * @param dto      metadata about the report
     * @param pdfFile  the PDF document (nullable – will be auto-generated if null/empty)
     * @return the saved ForensicReport
     */
    public ForensicReport createReport(ForensicReportDTO dto, MultipartFile pdfFile) {
        log.info("Creating forensic report: investigator={}, classification={}",
                dto.getForensicInvestigator(), dto.getClassification());

        // 0. Auto-generate PDF if none provided
        boolean autoGenerated = false;
        if (pdfFile == null || pdfFile.isEmpty()) {
            log.info("No PDF uploaded – auto-generating from form data");
            pdfFile = pdfGenerationService.generatePdf(dto);
            autoGenerated = true;
        }

        // 1. Upload PDF to MinIO
        String minioPath = minioService.uploadFile(pdfFile);
        log.debug("PDF uploaded to MinIO: {} (auto-generated={})", minioPath, autoGenerated);

        // 2. Extract text from PDF via Apache Tika
        String extractedContent = tikaService.extractText(pdfFile);
        log.debug("Extracted {} characters from PDF", extractedContent.length());

        // 3. Compute file hash (SHA-256)
        String fileHash = computeFileHash(pdfFile);

        // 4. Build ForensicReport entity
        ForensicReport report = new ForensicReport();
        report.setId(UUID.randomUUID().toString());
        report.setForensicInvestigator(dto.getForensicInvestigator());
        report.setOrganization(dto.getOrganization());
        report.setMalwareName(dto.getMalwareName());
        report.setDescription(dto.getDescription());
        report.setClassification(dto.getClassification());
        report.setFileHash(fileHash);
        report.setContent(extractedContent);
        report.setMinioPath(minioPath);
        report.setCity(dto.getCity());

        // 5. Set GeoPoint if coordinates provided
        if (dto.getLatitude() != null && dto.getLongitude() != null) {
            report.setLocation(new GeoPoint(dto.getLatitude(), dto.getLongitude()));
        }

        // 6. Save to Elasticsearch
        ForensicReport saved = repository.save(report);
        log.info("Forensic report saved with ID: {} (pdf={})", saved.getId(),
                autoGenerated ? "auto-generated" : "user-uploaded");

        // 7. Log statistics for Logstash pipeline
        statsService.logNewReport(saved);

        return saved;
    }

    /**
     * Retrieves a forensic report by ID.
     */
    public Optional<ForensicReport> getReportById(String id) {
        return repository.findById(id);
    }

    /**
     * Retrieves all forensic reports.
     */
    public List<ForensicReport> getAllReports() {
        List<ForensicReport> reports = new java.util.ArrayList<>();
        repository.findAll().forEach(reports::add);
        return reports;
    }

    /**
     * Deletes a forensic report by ID.
     */
    public void deleteReport(String id) {
        repository.deleteById(id);
        log.info("Forensic report deleted: {}", id);
    }

    // ==================== Private Helpers ====================

    /**
     * Computes SHA-256 hash of the uploaded file for integrity verification.
     */
    private String computeFileHash(MultipartFile file) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(file.getBytes());
            return HexFormat.of().formatHex(hash);
        } catch (Exception e) {
            log.warn("Failed to compute file hash", e);
            return "unknown";
        }
    }
}
